import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useEffect, useState } from "react";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { MapPin, Maximize2, CheckCircle2, Calendar, Filter, ChevronDown, DollarSign, Eye, Radio, Thermometer, User, Building2, Briefcase, Layers } from "lucide-react";
import { submitImageryRequest } from "@/lib/api/imageryRequests";
import { ApiError } from "@/lib/api/errorHandler";
import { FilterState } from "@/components/FilterPanel";
import { PriceEstimate } from "@/lib/utils/pricing";

// Request form schema
const requestFormSchema = z.object({
  full_name: z.string()
    .min(2, "Name must be at least 2 characters")
    .max(100, "Name must be less than 100 characters"),
  email: z.string()
    .email("Please enter a valid email address"),
  company: z.string()
    .max(100, "Company name must be less than 100 characters")
    .optional(),
  phone: z.string()
    .min(1, "Phone number is required")
    .max(20, "Phone number must be less than 20 characters"),
  use_case: z.string()
    .max(200, "Use case must be less than 200 characters")
    .optional(),
  data_type: z.enum(["optical", "radar", "thermal"], {
    required_error: "Please select a data type",
  }),
  start_date: z.date({
    required_error: "Start date is required",
  }),
  end_date: z.date({
    required_error: "End date is required",
  }),
  urgency: z.enum(["standard", "urgent", "emergency"], {
    required_error: "Please select an urgency level",
  }),
  additional_requirements: z.string()
    .max(2000, "Additional requirements must be less than 2000 characters")
    .optional(),
}).refine((data) => data.end_date >= data.start_date, {
  message: "End date must be after or equal to start date",
  path: ["end_date"],
});

export type RequestFormData = z.infer<typeof requestFormSchema>;

// AOI data interface
/**
 * AOI (Area of Interest) data structure passed to the RequestForm
 * This data is generated by the MapContainer component when a user draws a shape
 * 
 * @example
 * const aoiData: AOIData = {
 *   type: "polygon",
 *   geoJSON: { type: "Feature", geometry: {...}, properties: {} },
 *   coordinates: [[[10.0, 20.0], [10.0, 30.0], [20.0, 30.0], [20.0, 20.0], [10.0, 20.0]]],
 *   area: 123.45, // in km²
 *   center: { lat: 25.0, lng: 15.0 }
 * };
 */
export interface AOIData {
  type: string; // "polygon" | "rectangle"
  geoJSON: any;
  coordinates: number[][][];
  area: number; // in km²
  center: { lat: number; lng: number };
  layer?: any;
}

interface RequestFormProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  aoiData?: AOIData | null;
  filterState?: FilterState | null;
  onSubmitSuccess?: () => void;
  priceEstimate?: PriceEstimate | null;
  selectedDataType?: 'optical' | 'radar' | 'thermal' | null;
  duplicateRequestData?: {
    urgency?: string;
    additional_requirements?: string;
    date_range?: {
      start_date?: string;
      end_date?: string;
    };
  } | null;
}


const DATA_TYPES = [
  { value: 'optical', label: 'Optical', icon: Eye, desc: 'Visible & near-infrared' },
  { value: 'radar', label: 'SAR / Radar', icon: Radio, desc: 'All-weather, day & night' },
  { value: 'thermal', label: 'Thermal', icon: Thermometer, desc: 'Heat & temperature' },
] as const;

const USE_CASE_OPTIONS = [
  'Agriculture & Crop Monitoring',
  'Urban Planning & Development',
  'Disaster Response & Assessment',
  'Environmental Monitoring',
  'Infrastructure Inspection',
  'Maritime & Coastal Monitoring',
  'Forestry & Land Use',
  'Defence & Security',
  'Mining & Resources',
  'Other',
];

export const RequestForm = ({
  open,
  onOpenChange,
  aoiData,
  filterState,
  onSubmitSuccess,
  duplicateRequestData,
  priceEstimate,
  selectedDataType,
}: RequestFormProps) => {
  const { user, isAuthenticated } = useAuth();
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const [requestId, setRequestId] = useState<string | null>(null);
  
  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
    setValue,
    watch,
    control,
  } = useForm<RequestFormData>({
    resolver: zodResolver(requestFormSchema),
    defaultValues: {
      urgency: "standard",
      data_type: selectedDataType ?? "optical",
      start_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
      end_date: new Date(),
    },
  });

  const urgency = watch("urgency");
  const dataType = watch("data_type");

  // Calculate bounding box from coordinates
  const calculateBoundingBox = (coordinates: number[][][]) => {
    if (!coordinates || coordinates.length === 0 || coordinates[0].length === 0) {
      return null;
    }

    const points = coordinates[0];
    let minLng = points[0][0];
    let maxLng = points[0][0];
    let minLat = points[0][1];
    let maxLat = points[0][1];

    points.forEach(([lng, lat]) => {
      minLng = Math.min(minLng, lng);
      maxLng = Math.max(maxLng, lng);
      minLat = Math.min(minLat, lat);
      maxLat = Math.max(maxLat, lat);
    });

    return {
      north: maxLat.toFixed(6),
      south: minLat.toFixed(6),
      east: maxLng.toFixed(6),
      west: minLng.toFixed(6),
    };
  };

  const boundingBox = aoiData ? calculateBoundingBox(aoiData.coordinates) : null;

  // Auto-fill form with user data if logged in
  useEffect(() => {
    if (isAuthenticated && user) {
      if (user.full_name) {
        setValue("full_name", user.full_name);
      }
      if (user.email) {
        setValue("email", user.email);
      }
      if (user.company) {
        setValue("company", user.company);
      }
      if (user.phone) {
        setValue("phone", user.phone);
      }
    }
  }, [isAuthenticated, user, setValue]);

  // Sync selectedDataType from explorer sidebar
  useEffect(() => {
    if (selectedDataType && open) {
      setValue("data_type", selectedDataType);
    }
  }, [selectedDataType, open, setValue]);

  // Pre-fill form with duplicate request data
  useEffect(() => {
    if (duplicateRequestData && open) {
      if (duplicateRequestData.urgency) {
        setValue("urgency", duplicateRequestData.urgency as "standard" | "urgent" | "emergency");
      }
      if (duplicateRequestData.additional_requirements) {
        setValue("additional_requirements", duplicateRequestData.additional_requirements);
      }
      if (duplicateRequestData.date_range) {
        if (duplicateRequestData.date_range.start_date) {
          setValue("start_date", new Date(duplicateRequestData.date_range.start_date));
        }
        if (duplicateRequestData.date_range.end_date) {
          setValue("end_date", new Date(duplicateRequestData.date_range.end_date));
        }
      }
    }
  }, [duplicateRequestData, open, setValue]);

  // Reset success state when dialog closes
  useEffect(() => {
    if (!open) {
      setSubmitSuccess(false);
      setRequestId(null);
    }
  }, [open]);

  const handleFormSubmit = async (data: RequestFormData) => {
    // Validate that AOI data exists
    if (!aoiData) {
      toast({
        variant: "destructive",
        title: "Missing AOI",
        description: "Please draw an area of interest on the map before submitting.",
      });
      return;
    }

    setIsSubmitting(true);

    try {
      // Combine form data with AOI data and filters
      const payload = {
        full_name: data.full_name,
        email: data.email,
        company: data.company || undefined,
        phone: data.phone,
        use_case: data.use_case || undefined,
        data_type: data.data_type,
        aoi_type: aoiData.type,
        aoi_coordinates: {
          type: "Polygon",
          coordinates: aoiData.coordinates,
        },
        aoi_area_km2: aoiData.area,
        aoi_center: aoiData.center,
        date_range: {
          start_date: data.start_date.toISOString(),
          end_date: data.end_date.toISOString(),
        },
        filters: filterState ? {
          resolution_category: filterState.selectedResolutions.length > 0 ? filterState.selectedResolutions : undefined,
          max_cloud_coverage: filterState.cloudCoverage < 100 ? filterState.cloudCoverage : undefined,
          providers: filterState.selectedProviders.length > 0 ? filterState.selectedProviders : undefined,
          bands: filterState.selectedBands.length > 0 ? filterState.selectedBands : undefined,
          image_types: filterState.imageType ? [filterState.imageType] : undefined,
        } : undefined,
        urgency: data.urgency,
        additional_requirements: data.additional_requirements || undefined,
        estimated_archive_price: priceEstimate?.archive,
        estimated_tasking_price: priceEstimate?.tasking,
      };

      // Submit to API endpoint
      const response = await submitImageryRequest(payload);

      // Show success message
      setSubmitSuccess(true);
      setRequestId(response.request_id);
      
      toast({
        title: "Request Submitted Successfully!",
        description: `Your imagery request has been submitted. Request ID: ${response.request_id}`,
        duration: 5000,
      });

      // Reset form
      reset();

      // Notify parent of successful submission
      if (onSubmitSuccess) {
        onSubmitSuccess();
      }

      // Close dialog after a short delay to show success message
      setTimeout(() => {
        onOpenChange(false);
      }, 2000);

    } catch (error) {
      console.error('Error submitting imagery request:', error);
      
      // Show error message
      let errorMessage = "Failed to submit imagery request. Please try again.";
      
      if (error instanceof ApiError) {
        errorMessage = error.message;
        
        // Handle validation errors
        if (error.statusCode === 400 && error.data?.details) {
          const details = error.data.details;
          errorMessage = Object.values(details).join(', ');
        }
      }

      toast({
        variant: "destructive",
        title: "Submission Failed",
        description: errorMessage,
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] w-[95vw] sm:w-[90vw] md:w-full flex flex-col p-4 sm:p-6">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle className="text-base sm:text-lg md:text-xl">Request Satellite Imagery</DialogTitle>
          <DialogDescription className="text-xs sm:text-sm">
            Fill out the form below to submit your imagery request. We'll review your request and get back to you with a quote.
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto pr-1 sm:pr-2 dialog-scrollable">
          {submitSuccess ? (
            // Success State
            <div className="py-8 text-center space-y-4">
              <div className="flex justify-center">
                <div className="rounded-full bg-green-100 dark:bg-green-900/20 p-3">
                  <CheckCircle2 className="h-12 w-12 text-green-600 dark:text-green-400" />
                </div>
              </div>
              <div className="space-y-2">
                <h3 className="text-lg font-semibold">Request Submitted Successfully!</h3>
                <p className="text-muted-foreground">
                  Your imagery request has been received and is being processed.
                </p>
                {requestId && (
                  <p className="text-sm font-mono bg-muted px-3 py-2 rounded-md inline-block">
                    Request ID: {requestId}
                  </p>
                )}
              </div>
              <p className="text-sm text-muted-foreground">
                You will receive a confirmation email shortly with your request details.
                Our team will review your request and contact you with a quote.
              </p>
              <Button onClick={() => onOpenChange(false)} className="mt-4">
                Close
              </Button>
            </div>
          ) : (
            // Form State
            <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-4 sm:space-y-6 pb-4">
              {/* AOI Summary Display */}
              {aoiData && (
                <Card className="border-yellow-500 bg-slate-900 text-white">
                  <CardHeader className="pb-2 sm:pb-3 px-3 sm:px-6 pt-3 sm:pt-6">
                    <CardTitle className="text-xs sm:text-sm md:text-base flex items-center gap-2 text-white">
                      <MapPin className="h-3 w-3 sm:h-4 sm:w-4 text-yellow-400" />
                      Area of Interest Summary
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2 sm:space-y-3 px-3 sm:px-6 pb-3 sm:pb-6">
                    {/* AOI Type and Area */}
                    <div className="flex items-center gap-2 flex-wrap">
                      <Badge variant="outline" className="capitalize bg-slate-800 text-white border-slate-700 text-xs">
                        {aoiData.type}
                      </Badge>
                      <Badge className="font-mono bg-yellow-500 text-slate-900 hover:bg-yellow-600 text-xs">
                        <Maximize2 className="h-3 w-3 mr-1" />
                        {aoiData.area.toFixed(2)} km²
                      </Badge>
                    </div>

                    {/* Center Coordinates */}
                    <div className="space-y-1">
                      <p className="text-xs md:text-sm font-medium text-slate-300">Center Point</p>
                      <p className="text-xs md:text-sm font-mono text-white break-all">
                        {aoiData.center.lat.toFixed(6)}°, {aoiData.center.lng.toFixed(6)}°
                      </p>
                    </div>

                    {/* Vertex Coordinates for Polygon/Rectangle */}
                    {(aoiData.type === 'polygon' || aoiData.type === 'rectangle') && aoiData.coordinates && aoiData.coordinates[0] && (
                      <Collapsible>
                        <div className="space-y-1">
                          <CollapsibleTrigger className="flex items-center justify-between w-full text-xs md:text-sm font-medium text-slate-300 hover:text-white transition-colors">
                            <span>Vertex Coordinates</span>
                            <ChevronDown className="h-4 w-4 transition-transform duration-200 data-[state=open]:rotate-180" />
                          </CollapsibleTrigger>
                          <CollapsibleContent className="pt-2">
                            <div className="max-h-48 overflow-y-auto space-y-1 pr-1">
                              {aoiData.coordinates[0].slice(0, -1).map((coord: number[], index: number) => (
                                <div key={index} className="flex justify-between items-center text-xs md:text-sm">
                                  <span className="text-slate-400">Vertex {index + 1}:</span>
                                  <span className="font-mono text-white">
                                    {coord[1].toFixed(4)}°, {coord[0].toFixed(4)}°
                                  </span>
                                </div>
                              ))}
                            </div>
                          </CollapsibleContent>
                        </div>
                      </Collapsible>
                    )}

                    {/* Bounding Box */}
                    {boundingBox && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Bounding Box</p>
                        <div className="grid grid-cols-2 gap-1 md:gap-2 text-xs md:text-sm font-mono text-white">
                          <div>
                            <span className="text-slate-400">North:</span> {boundingBox.north}°
                          </div>
                          <div>
                            <span className="text-slate-400">South:</span> {boundingBox.south}°
                          </div>
                          <div>
                            <span className="text-slate-400">East:</span> {boundingBox.east}°
                          </div>
                          <div>
                            <span className="text-slate-400">West:</span> {boundingBox.west}°
                          </div>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

              {/* Price Estimate Card */}
              {priceEstimate && (
                <Card className="border-yellow-500/50 bg-slate-900 text-white">
                  <CardHeader className="pb-2 px-3 sm:px-6 pt-3 sm:pt-6">
                    <CardTitle className="text-xs sm:text-sm md:text-base flex items-center gap-2 text-white">
                      <DollarSign className="h-3 w-3 sm:h-4 sm:w-4 text-yellow-400" />
                      Price Estimate
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="px-3 sm:px-6 pb-3 sm:pb-6">
                    <div className="grid grid-cols-2 gap-3">
                      <div className="bg-slate-800 rounded-lg p-3 text-center">
                        <p className="text-xs text-slate-400 mb-1">Archive</p>
                        <p className="text-lg font-bold text-yellow-400">${priceEstimate.archive.toFixed(2)}</p>
                        <p className="text-xs text-slate-500">Existing imagery</p>
                      </div>
                      <div className="bg-slate-800 rounded-lg p-3 text-center">
                        <p className="text-xs text-slate-400 mb-1">Tasking</p>
                        <p className="text-lg font-bold text-yellow-400">${priceEstimate.tasking.toFixed(2)}</p>
                        <p className="text-xs text-slate-500">New collection</p>
                      </div>
                    </div>
                    <p className="text-xs text-slate-500 mt-2">
                      <span className="font-medium text-slate-400">Estimate Only.</span> Final pricing subject to provider availability and service agreements.
                    </p>
                  </CardContent>
                </Card>
              )}

              {/* Filter Summary Display */}
              {filterState && (
                filterState.selectedResolutions.length > 0 ||
                filterState.cloudCoverage < 100 ||
                filterState.selectedProviders.length > 0 ||
                filterState.selectedBands.length > 0 ||
                filterState.imageType ||
                filterState.dateRange.startDate ||
                filterState.dateRange.endDate
              ) && (
                <Card className="border-blue-500 bg-slate-900 text-white">
                  <CardHeader className="pb-2 sm:pb-3 px-3 sm:px-6 pt-3 sm:pt-6">
                    <CardTitle className="text-xs sm:text-sm md:text-base flex items-center gap-2 text-white">
                      <Filter className="h-3 w-3 sm:h-4 sm:w-4 text-blue-400" />
                      Applied Filters
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2 sm:space-y-3 px-3 sm:px-6 pb-3 sm:pb-6">
                    {/* Date Range */}
                    {(filterState.dateRange.startDate || filterState.dateRange.endDate) && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Date Range</p>
                        <p className="text-xs md:text-sm text-white">
                          {filterState.dateRange.startDate?.toLocaleDateString() || 'Any'} - {filterState.dateRange.endDate?.toLocaleDateString() || 'Any'}
                        </p>
                      </div>
                    )}

                    {/* Resolution */}
                    {filterState.selectedResolutions.length > 0 && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Resolution</p>
                        <div className="flex flex-wrap gap-1">
                          {filterState.selectedResolutions.map((res) => (
                            <Badge key={res} variant="outline" className="bg-slate-800 text-white border-slate-700 text-xs uppercase">
                              {res}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Cloud Coverage */}
                    {filterState.cloudCoverage < 100 && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Max Cloud Coverage</p>
                        <p className="text-xs md:text-sm text-white">≤ {filterState.cloudCoverage}%</p>
                      </div>
                    )}

                    {/* Providers */}
                    {filterState.selectedProviders.length > 0 && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Providers</p>
                        <div className="flex flex-wrap gap-1">
                          {filterState.selectedProviders.map((provider) => (
                            <Badge key={provider} variant="outline" className="bg-slate-800 text-white border-slate-700 text-xs">
                              {provider}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Bands */}
                    {filterState.selectedBands.length > 0 && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Bands</p>
                        <div className="flex flex-wrap gap-1">
                          {filterState.selectedBands.map((band) => (
                            <Badge key={band} variant="outline" className="bg-slate-800 text-white border-slate-700 text-xs">
                              {band}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Image Type */}
                    {filterState.imageType && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Image Type</p>
                        <Badge variant="outline" className="bg-slate-800 text-white border-slate-700 text-xs capitalize">
                          {filterState.imageType}
                        </Badge>
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

          {/* ── Section: Contact Details ── */}
          <div className="space-y-3 sm:space-y-4">
            <div className="flex items-center gap-2 pb-1 border-b border-slate-700">
              <User className="h-4 w-4 text-yellow-400" />
              <h3 className="text-sm font-semibold text-slate-200">Contact Details</h3>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {/* Full Name */}
              <div className="space-y-1.5">
                <Label htmlFor="full_name" className="text-xs text-slate-300">Full Name *</Label>
                <Input
                  id="full_name"
                  placeholder="Jane Smith"
                  {...register("full_name")}
                  aria-invalid={errors.full_name ? "true" : "false"}
                  className="min-h-[44px] bg-slate-800 border-slate-600 text-white placeholder:text-slate-500 focus:border-yellow-500"
                />
                {errors.full_name && <p className="text-xs text-destructive">{errors.full_name.message}</p>}
              </div>

              {/* Email */}
              <div className="space-y-1.5">
                <Label htmlFor="email" className="text-xs text-slate-300">Email Address *</Label>
                <Input
                  id="email"
                  type="email"
                  placeholder="jane@company.com"
                  {...register("email")}
                  aria-invalid={errors.email ? "true" : "false"}
                  className="min-h-[44px] bg-slate-800 border-slate-600 text-white placeholder:text-slate-500 focus:border-yellow-500"
                />
                {errors.email && <p className="text-xs text-destructive">{errors.email.message}</p>}
              </div>

              {/* Company */}
              <div className="space-y-1.5">
                <Label htmlFor="company" className="text-xs text-slate-300">Company</Label>
                <div className="relative">
                  <Building2 className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
                  <Input
                    id="company"
                    placeholder="Organisation"
                    {...register("company")}
                    className="min-h-[44px] pl-9 bg-slate-800 border-slate-600 text-white placeholder:text-slate-500 focus:border-yellow-500"
                  />
                </div>
                {errors.company && <p className="text-xs text-destructive">{errors.company.message}</p>}
              </div>

              {/* Phone */}
              <div className="space-y-1.5">
                <Label htmlFor="phone" className="text-xs text-slate-300">Phone Number</Label>
                <Input
                  id="phone"
                  type="tel"
                  placeholder="+1 (555) 123-4567"
                  {...register("phone")}
                  className="min-h-[44px] bg-slate-800 border-slate-600 text-white placeholder:text-slate-500 focus:border-yellow-500"
                />
                {errors.phone && <p className="text-xs text-destructive">{errors.phone.message}</p>}
              </div>
            </div>

            {/* Use Case */}
            <div className="space-y-1.5">
              <Label htmlFor="use_case" className="text-xs text-slate-300 flex items-center gap-1.5">
                <Briefcase className="h-3.5 w-3.5" /> Use Case
              </Label>
              <Select onValueChange={(v) => setValue("use_case", v)}>
                <SelectTrigger className="min-h-[44px] bg-slate-800 border-slate-600 text-white">
                  <SelectValue placeholder="Select your use case..." />
                </SelectTrigger>
                <SelectContent>
                  {USE_CASE_OPTIONS.map((uc) => (
                    <SelectItem key={uc} value={uc}>{uc}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          {/* ── Section: Data Type ── */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 pb-1 border-b border-slate-700">
              <Layers className="h-4 w-4 text-yellow-400" />
              <h3 className="text-sm font-semibold text-slate-200">Data Type *</h3>
            </div>
            <div className="grid grid-cols-3 gap-2">
              {DATA_TYPES.map(({ value, label, icon: Icon, desc }) => (
                <button
                  key={value}
                  type="button"
                  onClick={() => setValue("data_type", value)}
                  className={`flex flex-col items-center gap-1.5 p-3 rounded-lg border text-xs transition-all ${
                    dataType === value
                      ? 'bg-yellow-500/10 border-yellow-500 text-yellow-400'
                      : 'bg-slate-800 border-slate-600 text-slate-300 hover:border-slate-500 hover:text-white'
                  }`}
                >
                  <Icon className="h-5 w-5" />
                  <span className="font-semibold">{label}</span>
                  <span className="text-[10px] text-slate-500 text-center leading-tight">{desc}</span>
                </button>
              ))}
            </div>
            {errors.data_type && <p className="text-xs text-destructive">{errors.data_type.message}</p>}
          </div>

          {/* ── Section: Date Range & Urgency ── */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 pb-1 border-b border-slate-700">
              <Calendar className="h-4 w-4 text-yellow-400" />
              <h3 className="text-sm font-semibold text-slate-200">Date Range & Urgency</h3>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <div className="space-y-1.5">
                <Label className="text-xs text-slate-300">Start Date *</Label>
                <Controller
                  name="start_date"
                  control={control}
                  render={({ field }) => (
                    <DatePicker
                      selected={field.value}
                      onChange={(date) => field.onChange(date)}
                      maxDate={watch("end_date") || new Date()}
                      dateFormat="MMM d, yyyy"
                      className="w-full px-3 py-2 text-sm rounded-md border border-slate-600 bg-slate-800 text-white min-h-[44px] focus:outline-none focus:border-yellow-500"
                      placeholderText="Select start date"
                    />
                  )}
                />
                {errors.start_date && <p className="text-xs text-destructive">{errors.start_date.message}</p>}
              </div>

              <div className="space-y-1.5">
                <Label className="text-xs text-slate-300">End Date *</Label>
                <Controller
                  name="end_date"
                  control={control}
                  render={({ field }) => (
                    <DatePicker
                      selected={field.value}
                      onChange={(date) => field.onChange(date)}
                      minDate={watch("start_date")}
                      maxDate={new Date()}
                      dateFormat="MMM d, yyyy"
                      className="w-full px-3 py-2 text-sm rounded-md border border-slate-600 bg-slate-800 text-white min-h-[44px] focus:outline-none focus:border-yellow-500"
                      placeholderText="Select end date"
                    />
                  )}
                />
                {errors.end_date && <p className="text-xs text-destructive">{errors.end_date.message}</p>}
              </div>
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="urgency" className="text-xs text-slate-300">Urgency Level *</Label>
              <Select
                value={urgency}
                onValueChange={(value) => setValue("urgency", value as "standard" | "urgent" | "emergency")}
              >
                <SelectTrigger id="urgency" className="min-h-[44px] bg-slate-800 border-slate-600 text-white">
                  <SelectValue placeholder="Select urgency level" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="standard">🕐 Standard — 5–7 business days</SelectItem>
                  <SelectItem value="urgent">⚡ Urgent — 2–3 business days</SelectItem>
                  <SelectItem value="emergency">🚨 Emergency — 24–48 hours</SelectItem>
                </SelectContent>
              </Select>
              {errors.urgency && <p className="text-xs text-destructive">{errors.urgency.message}</p>}
            </div>
          </div>

          {/* ── Section: Additional Requirements ── */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 pb-1 border-b border-slate-700">
              <Filter className="h-4 w-4 text-yellow-400" />
              <h3 className="text-sm font-semibold text-slate-200">Additional Requirements</h3>
            </div>
            <Textarea
              id="additional_requirements"
              placeholder="Describe any specific requirements — e.g. off-nadir angle, stereo pairs, delivery format, processing level..."
              rows={4}
              {...register("additional_requirements")}
              className="min-h-[100px] resize-y bg-slate-800 border-slate-600 text-white placeholder:text-slate-500 focus:border-yellow-500"
            />
            {errors.additional_requirements && (
              <p className="text-xs text-destructive">{errors.additional_requirements.message}</p>
            )}
          </div>

          {/* Submit Button */}
          <div className="flex flex-col sm:flex-row justify-end gap-2 sm:gap-3 pt-4 border-t border-slate-700">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isSubmitting}
              className="w-full sm:w-auto min-h-[44px] order-2 sm:order-1 border-slate-600 text-slate-300 hover:bg-slate-800"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isSubmitting || !aoiData}
              className="w-full sm:w-auto bg-yellow-500 hover:bg-yellow-600 text-slate-900 font-semibold min-h-[44px] order-1 sm:order-2 disabled:opacity-50"
            >
              {isSubmitting ? "Submitting..." : "Submit Request"}
            </Button>
          </div>
        </form>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};
