import { useForm, Controller } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { useEffect, useState } from "react";
import DatePicker from "react-datepicker";
import "react-datepicker/dist/react-datepicker.css";
import { useAuth } from "@/contexts/AuthContext";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
import { MapPin, Maximize2, CheckCircle2, Calendar, Filter, ChevronDown } from "lucide-react";
import { submitImageryRequest } from "@/lib/api/imageryRequests";
import { ApiError } from "@/lib/api/errorHandler";
import { FilterState } from "@/components/FilterPanel";

// Request form schema
const requestFormSchema = z.object({
  full_name: z.string()
    .min(2, "Name must be at least 2 characters")
    .max(100, "Name must be less than 100 characters"),
  email: z.string()
    .email("Please enter a valid email address"),
  company: z.string()
    .max(100, "Company name must be less than 100 characters")
    .optional(),
  phone: z.string()
    .max(20, "Phone number must be less than 20 characters")
    .optional(),
  start_date: z.date({
    required_error: "Start date is required",
  }),
  end_date: z.date({
    required_error: "End date is required",
  }),
  urgency: z.enum(["standard", "urgent", "emergency"], {
    required_error: "Please select an urgency level",
  }),
  additional_requirements: z.string()
    .max(2000, "Additional requirements must be less than 2000 characters")
    .optional(),
}).refine((data) => data.end_date >= data.start_date, {
  message: "End date must be after or equal to start date",
  path: ["end_date"],
});

export type RequestFormData = z.infer<typeof requestFormSchema>;

// AOI data interface
/**
 * AOI (Area of Interest) data structure passed to the RequestForm
 * This data is generated by the MapContainer component when a user draws a shape
 * 
 * @example
 * const aoiData: AOIData = {
 *   type: "polygon",
 *   geoJSON: { type: "Feature", geometry: {...}, properties: {} },
 *   coordinates: [[[10.0, 20.0], [10.0, 30.0], [20.0, 30.0], [20.0, 20.0], [10.0, 20.0]]],
 *   area: 123.45, // in km²
 *   center: { lat: 25.0, lng: 15.0 }
 * };
 */
export interface AOIData {
  type: string; // "polygon" | "rectangle"
  geoJSON: any;
  coordinates: number[][][];
  area: number; // in km²
  center: { lat: number; lng: number };
  layer?: any;
}

interface RequestFormProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  aoiData?: AOIData | null;
  filterState?: FilterState | null;
  onSubmitSuccess?: () => void;
  duplicateRequestData?: {
    urgency?: string;
    additional_requirements?: string;
    date_range?: {
      start_date?: string;
      end_date?: string;
    };
  } | null;
}


export const RequestForm = ({
  open,
  onOpenChange,
  aoiData,
  filterState,
  onSubmitSuccess,
  duplicateRequestData,
}: RequestFormProps) => {
  const { user, isAuthenticated } = useAuth();
  const { toast } = useToast();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitSuccess, setSubmitSuccess] = useState(false);
  const [requestId, setRequestId] = useState<string | null>(null);
  
  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
    setValue,
    watch,
    control,
  } = useForm<RequestFormData>({
    resolver: zodResolver(requestFormSchema),
    defaultValues: {
      urgency: "standard",
      start_date: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), // 30 days ago
      end_date: new Date(), // Today
    },
  });

  const urgency = watch("urgency");

  // Calculate bounding box from coordinates
  const calculateBoundingBox = (coordinates: number[][][]) => {
    if (!coordinates || coordinates.length === 0 || coordinates[0].length === 0) {
      return null;
    }

    const points = coordinates[0];
    let minLng = points[0][0];
    let maxLng = points[0][0];
    let minLat = points[0][1];
    let maxLat = points[0][1];

    points.forEach(([lng, lat]) => {
      minLng = Math.min(minLng, lng);
      maxLng = Math.max(maxLng, lng);
      minLat = Math.min(minLat, lat);
      maxLat = Math.max(maxLat, lat);
    });

    return {
      north: maxLat.toFixed(6),
      south: minLat.toFixed(6),
      east: maxLng.toFixed(6),
      west: minLng.toFixed(6),
    };
  };

  const boundingBox = aoiData ? calculateBoundingBox(aoiData.coordinates) : null;

  // Auto-fill form with user data if logged in
  useEffect(() => {
    if (isAuthenticated && user) {
      if (user.full_name) {
        setValue("full_name", user.full_name);
      }
      if (user.email) {
        setValue("email", user.email);
      }
      if (user.company) {
        setValue("company", user.company);
      }
    }
  }, [isAuthenticated, user, setValue]);

  // Pre-fill form with duplicate request data
  useEffect(() => {
    if (duplicateRequestData && open) {
      if (duplicateRequestData.urgency) {
        setValue("urgency", duplicateRequestData.urgency as "standard" | "urgent" | "emergency");
      }
      if (duplicateRequestData.additional_requirements) {
        setValue("additional_requirements", duplicateRequestData.additional_requirements);
      }
      if (duplicateRequestData.date_range) {
        if (duplicateRequestData.date_range.start_date) {
          setValue("start_date", new Date(duplicateRequestData.date_range.start_date));
        }
        if (duplicateRequestData.date_range.end_date) {
          setValue("end_date", new Date(duplicateRequestData.date_range.end_date));
        }
      }
    }
  }, [duplicateRequestData, open, setValue]);

  // Reset success state when dialog closes
  useEffect(() => {
    if (!open) {
      setSubmitSuccess(false);
      setRequestId(null);
    }
  }, [open]);

  const handleFormSubmit = async (data: RequestFormData) => {
    // Validate that AOI data exists
    if (!aoiData) {
      toast({
        variant: "destructive",
        title: "Missing AOI",
        description: "Please draw an area of interest on the map before submitting.",
      });
      return;
    }

    setIsSubmitting(true);

    try {
      // Combine form data with AOI data and filters
      const payload = {
        full_name: data.full_name,
        email: data.email,
        company: data.company || undefined,
        phone: data.phone || undefined,
        aoi_type: aoiData.type,
        aoi_coordinates: {
          type: "Polygon",
          coordinates: aoiData.coordinates,
        },
        aoi_area_km2: aoiData.area,
        aoi_center: aoiData.center,
        // Use dates from form
        date_range: {
          start_date: data.start_date.toISOString(),
          end_date: data.end_date.toISOString(),
        },
        // Include filters if available
        filters: filterState ? {
          resolution_category: filterState.selectedResolutions.length > 0 ? filterState.selectedResolutions : undefined,
          max_cloud_coverage: filterState.cloudCoverage < 100 ? filterState.cloudCoverage : undefined,
          providers: filterState.selectedProviders.length > 0 ? filterState.selectedProviders : undefined,
          bands: filterState.selectedBands.length > 0 ? filterState.selectedBands : undefined,
          image_types: filterState.imageType ? [filterState.imageType] : undefined,
        } : undefined,
        urgency: data.urgency,
        additional_requirements: data.additional_requirements || undefined,
      };

      // Submit to API endpoint
      const response = await submitImageryRequest(payload);

      // Show success message
      setSubmitSuccess(true);
      setRequestId(response.request_id);
      
      toast({
        title: "Request Submitted Successfully!",
        description: `Your imagery request has been submitted. Request ID: ${response.request_id}`,
        duration: 5000,
      });

      // Reset form
      reset();

      // Notify parent of successful submission
      if (onSubmitSuccess) {
        onSubmitSuccess();
      }

      // Close dialog after a short delay to show success message
      setTimeout(() => {
        onOpenChange(false);
      }, 2000);

    } catch (error) {
      console.error('Error submitting imagery request:', error);
      
      // Show error message
      let errorMessage = "Failed to submit imagery request. Please try again.";
      
      if (error instanceof ApiError) {
        errorMessage = error.message;
        
        // Handle validation errors
        if (error.statusCode === 400 && error.data?.details) {
          const details = error.data.details;
          errorMessage = Object.values(details).join(', ');
        }
      }

      toast({
        variant: "destructive",
        title: "Submission Failed",
        description: errorMessage,
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl max-h-[90vh] w-[95vw] sm:w-[90vw] md:w-full flex flex-col p-4 sm:p-6">
        <DialogHeader className="flex-shrink-0">
          <DialogTitle className="text-base sm:text-lg md:text-xl">Request Satellite Imagery</DialogTitle>
          <DialogDescription className="text-xs sm:text-sm">
            Fill out the form below to submit your imagery request. We'll review your request and get back to you with a quote.
          </DialogDescription>
        </DialogHeader>

        <div className="flex-1 overflow-y-auto pr-1 sm:pr-2 dialog-scrollable">
          {submitSuccess ? (
            // Success State
            <div className="py-8 text-center space-y-4">
              <div className="flex justify-center">
                <div className="rounded-full bg-green-100 dark:bg-green-900/20 p-3">
                  <CheckCircle2 className="h-12 w-12 text-green-600 dark:text-green-400" />
                </div>
              </div>
              <div className="space-y-2">
                <h3 className="text-lg font-semibold">Request Submitted Successfully!</h3>
                <p className="text-muted-foreground">
                  Your imagery request has been received and is being processed.
                </p>
                {requestId && (
                  <p className="text-sm font-mono bg-muted px-3 py-2 rounded-md inline-block">
                    Request ID: {requestId}
                  </p>
                )}
              </div>
              <p className="text-sm text-muted-foreground">
                You will receive a confirmation email shortly with your request details.
                Our team will review your request and contact you with a quote.
              </p>
              <Button onClick={() => onOpenChange(false)} className="mt-4">
                Close
              </Button>
            </div>
          ) : (
            // Form State
            <form onSubmit={handleSubmit(handleFormSubmit)} className="space-y-4 sm:space-y-6 pb-4">
              {/* AOI Summary Display */}
              {aoiData && (
                <Card className="border-yellow-500 bg-slate-900 text-white">
                  <CardHeader className="pb-2 sm:pb-3 px-3 sm:px-6 pt-3 sm:pt-6">
                    <CardTitle className="text-xs sm:text-sm md:text-base flex items-center gap-2 text-white">
                      <MapPin className="h-3 w-3 sm:h-4 sm:w-4 text-yellow-400" />
                      Area of Interest Summary
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2 sm:space-y-3 px-3 sm:px-6 pb-3 sm:pb-6">
                    {/* AOI Type and Area */}
                    <div className="flex items-center gap-2 flex-wrap">
                      <Badge variant="outline" className="capitalize bg-slate-800 text-white border-slate-700 text-xs">
                        {aoiData.type}
                      </Badge>
                      <Badge className="font-mono bg-yellow-500 text-slate-900 hover:bg-yellow-600 text-xs">
                        <Maximize2 className="h-3 w-3 mr-1" />
                        {aoiData.area.toFixed(2)} km²
                      </Badge>
                    </div>

                    {/* Center Coordinates */}
                    <div className="space-y-1">
                      <p className="text-xs md:text-sm font-medium text-slate-300">Center Point</p>
                      <p className="text-xs md:text-sm font-mono text-white break-all">
                        {aoiData.center.lat.toFixed(6)}°, {aoiData.center.lng.toFixed(6)}°
                      </p>
                    </div>

                    {/* Vertex Coordinates for Polygon/Rectangle */}
                    {(aoiData.type === 'polygon' || aoiData.type === 'rectangle') && aoiData.coordinates && aoiData.coordinates[0] && (
                      <Collapsible>
                        <div className="space-y-1">
                          <CollapsibleTrigger className="flex items-center justify-between w-full text-xs md:text-sm font-medium text-slate-300 hover:text-white transition-colors">
                            <span>Vertex Coordinates</span>
                            <ChevronDown className="h-4 w-4 transition-transform duration-200 data-[state=open]:rotate-180" />
                          </CollapsibleTrigger>
                          <CollapsibleContent className="pt-2">
                            <div className="max-h-48 overflow-y-auto space-y-1 pr-1">
                              {aoiData.coordinates[0].slice(0, -1).map((coord: number[], index: number) => (
                                <div key={index} className="flex justify-between items-center text-xs md:text-sm">
                                  <span className="text-slate-400">Vertex {index + 1}:</span>
                                  <span className="font-mono text-white">
                                    {coord[1].toFixed(4)}°, {coord[0].toFixed(4)}°
                                  </span>
                                </div>
                              ))}
                            </div>
                          </CollapsibleContent>
                        </div>
                      </Collapsible>
                    )}

                    {/* Bounding Box */}
                    {boundingBox && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Bounding Box</p>
                        <div className="grid grid-cols-2 gap-1 md:gap-2 text-xs md:text-sm font-mono text-white">
                          <div>
                            <span className="text-slate-400">North:</span> {boundingBox.north}°
                          </div>
                          <div>
                            <span className="text-slate-400">South:</span> {boundingBox.south}°
                          </div>
                          <div>
                            <span className="text-slate-400">East:</span> {boundingBox.east}°
                          </div>
                          <div>
                            <span className="text-slate-400">West:</span> {boundingBox.west}°
                          </div>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

              {/* Filter Summary Display */}
              {filterState && (
                filterState.selectedResolutions.length > 0 ||
                filterState.cloudCoverage < 100 ||
                filterState.selectedProviders.length > 0 ||
                filterState.selectedBands.length > 0 ||
                filterState.imageType ||
                filterState.dateRange.startDate ||
                filterState.dateRange.endDate
              ) && (
                <Card className="border-blue-500 bg-slate-900 text-white">
                  <CardHeader className="pb-2 sm:pb-3 px-3 sm:px-6 pt-3 sm:pt-6">
                    <CardTitle className="text-xs sm:text-sm md:text-base flex items-center gap-2 text-white">
                      <Filter className="h-3 w-3 sm:h-4 sm:w-4 text-blue-400" />
                      Applied Filters
                    </CardTitle>
                  </CardHeader>
                  <CardContent className="space-y-2 sm:space-y-3 px-3 sm:px-6 pb-3 sm:pb-6">
                    {/* Date Range */}
                    {(filterState.dateRange.startDate || filterState.dateRange.endDate) && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Date Range</p>
                        <p className="text-xs md:text-sm text-white">
                          {filterState.dateRange.startDate?.toLocaleDateString() || 'Any'} - {filterState.dateRange.endDate?.toLocaleDateString() || 'Any'}
                        </p>
                      </div>
                    )}

                    {/* Resolution */}
                    {filterState.selectedResolutions.length > 0 && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Resolution</p>
                        <div className="flex flex-wrap gap-1">
                          {filterState.selectedResolutions.map((res) => (
                            <Badge key={res} variant="outline" className="bg-slate-800 text-white border-slate-700 text-xs uppercase">
                              {res}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Cloud Coverage */}
                    {filterState.cloudCoverage < 100 && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Max Cloud Coverage</p>
                        <p className="text-xs md:text-sm text-white">≤ {filterState.cloudCoverage}%</p>
                      </div>
                    )}

                    {/* Providers */}
                    {filterState.selectedProviders.length > 0 && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Providers</p>
                        <div className="flex flex-wrap gap-1">
                          {filterState.selectedProviders.map((provider) => (
                            <Badge key={provider} variant="outline" className="bg-slate-800 text-white border-slate-700 text-xs">
                              {provider}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Bands */}
                    {filterState.selectedBands.length > 0 && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Bands</p>
                        <div className="flex flex-wrap gap-1">
                          {filterState.selectedBands.map((band) => (
                            <Badge key={band} variant="outline" className="bg-slate-800 text-white border-slate-700 text-xs">
                              {band}
                            </Badge>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* Image Type */}
                    {filterState.imageType && (
                      <div className="space-y-1">
                        <p className="text-xs md:text-sm font-medium text-slate-300">Image Type</p>
                        <Badge variant="outline" className="bg-slate-800 text-white border-slate-700 text-xs capitalize">
                          {filterState.imageType}
                        </Badge>
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

          {/* Full Name */}
          <div className="space-y-1.5 sm:space-y-2">
            <Label htmlFor="full_name" className="text-sm">Full Name *</Label>
            <Input
              id="full_name"
              placeholder="John Doe"
              {...register("full_name")}
              aria-invalid={errors.full_name ? "true" : "false"}
              aria-describedby={errors.full_name ? "full_name-error" : undefined}
              className="min-h-[44px]"
            />
            {errors.full_name && (
              <p id="full_name-error" className="text-xs sm:text-sm text-destructive">
                {errors.full_name.message}
              </p>
            )}
          </div>

          {/* Email */}
          <div className="space-y-1.5 sm:space-y-2">
            <Label htmlFor="email" className="text-sm">Email Address *</Label>
            <Input
              id="email"
              type="email"
              placeholder="john.doe@company.com"
              {...register("email")}
              aria-invalid={errors.email ? "true" : "false"}
              aria-describedby={errors.email ? "email-error" : undefined}
              className="min-h-[44px]"
            />
            {errors.email && (
              <p id="email-error" className="text-xs sm:text-sm text-destructive">
                {errors.email.message}
              </p>
            )}
          </div>

          {/* Company */}
          <div className="space-y-1.5 sm:space-y-2">
            <Label htmlFor="company" className="text-sm">Company</Label>
            <Input
              id="company"
              placeholder="Your Company"
              {...register("company")}
              aria-invalid={errors.company ? "true" : "false"}
              aria-describedby={errors.company ? "company-error" : undefined}
              className="min-h-[44px]"
            />
            {errors.company && (
              <p id="company-error" className="text-xs sm:text-sm text-destructive">
                {errors.company.message}
              </p>
            )}
          </div>

          {/* Phone */}
          <div className="space-y-1.5 sm:space-y-2">
            <Label htmlFor="phone" className="text-sm">Phone Number</Label>
            <Input
              id="phone"
              type="tel"
              placeholder="+1 (555) 123-4567"
              {...register("phone")}
              aria-invalid={errors.phone ? "true" : "false"}
              aria-describedby={errors.phone ? "phone-error" : undefined}
              className="min-h-[44px]"
            />
            {errors.phone && (
              <p id="phone-error" className="text-xs sm:text-sm text-destructive">
                {errors.phone.message}
              </p>
            )}
          </div>

          {/* Date Range */}
          <div className="space-y-1.5 sm:space-y-2">
            <Label className="flex items-center gap-2 text-sm">
              <Calendar className="h-3 w-3 sm:h-4 sm:w-4" />
              Date Range *
            </Label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 sm:gap-4">
              {/* Start Date */}
              <div className="space-y-1.5 sm:space-y-2">
                <Label htmlFor="start_date" className="text-xs text-muted-foreground">Start Date</Label>
                <Controller
                  name="start_date"
                  control={control}
                  render={({ field }) => (
                    <DatePicker
                      selected={field.value}
                      onChange={(date) => field.onChange(date)}
                      maxDate={watch("end_date") || new Date()}
                      dateFormat="MMM d, yyyy"
                      className="w-full px-3 py-2 text-sm rounded-md border border-input bg-background min-h-[44px]"
                      placeholderText="Select start date"
                    />
                  )}
                />
                {errors.start_date && (
                  <p className="text-xs sm:text-sm text-destructive">
                    {errors.start_date.message}
                  </p>
                )}
              </div>

              {/* End Date */}
              <div className="space-y-1.5 sm:space-y-2">
                <Label htmlFor="end_date" className="text-xs text-muted-foreground">End Date</Label>
                <Controller
                  name="end_date"
                  control={control}
                  render={({ field }) => (
                    <DatePicker
                      selected={field.value}
                      onChange={(date) => field.onChange(date)}
                      minDate={watch("start_date")}
                      maxDate={new Date()}
                      dateFormat="MMM d, yyyy"
                      className="w-full px-3 py-2 text-sm rounded-md border border-input bg-background min-h-[44px]"
                      placeholderText="Select end date"
                    />
                  )}
                />
                {errors.end_date && (
                  <p className="text-xs sm:text-sm text-destructive">
                    {errors.end_date.message}
                  </p>
                )}
              </div>
            </div>
            <p className="text-xs text-muted-foreground">
              Select the date range for imagery you're interested in
            </p>
          </div>

          {/* Urgency */}
          <div className="space-y-1.5 sm:space-y-2">
            <Label htmlFor="urgency" className="text-sm">Urgency Level *</Label>
            <Select
              value={urgency}
              onValueChange={(value) => setValue("urgency", value as "standard" | "urgent" | "emergency")}
            >
              <SelectTrigger id="urgency" aria-describedby={errors.urgency ? "urgency-error" : undefined} className="min-h-[44px]">
                <SelectValue placeholder="Select urgency level" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="standard">Standard (5-7 business days)</SelectItem>
                <SelectItem value="urgent">Urgent (2-3 business days)</SelectItem>
                <SelectItem value="emergency">Emergency (24-48 hours)</SelectItem>
              </SelectContent>
            </Select>
            {errors.urgency && (
              <p id="urgency-error" className="text-xs sm:text-sm text-destructive">
                {errors.urgency.message}
              </p>
            )}
          </div>

          {/* Additional Requirements */}
          <div className="space-y-1.5 sm:space-y-2">
            <Label htmlFor="additional_requirements" className="text-sm">Additional Requirements</Label>
            <Textarea
              id="additional_requirements"
              placeholder="Please provide any additional details about your imagery requirements..."
              rows={4}
              {...register("additional_requirements")}
              aria-invalid={errors.additional_requirements ? "true" : "false"}
              aria-describedby={errors.additional_requirements ? "additional_requirements-error" : undefined}
              className="min-h-[100px] resize-y"
            />
            {errors.additional_requirements && (
              <p id="additional_requirements-error" className="text-xs sm:text-sm text-destructive">
                {errors.additional_requirements.message}
              </p>
            )}
          </div>

          {/* Submit Button */}
          <div className="flex flex-col sm:flex-row justify-end gap-2 sm:gap-3 pt-4 border-t">
            <Button
              type="button"
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={isSubmitting}
              className="w-full sm:w-auto min-h-[44px] order-2 sm:order-1"
            >
              Cancel
            </Button>
            <Button
              type="submit"
              disabled={isSubmitting || !aoiData}
              className="w-full sm:w-auto bg-yellow-500 hover:bg-yellow-600 text-slate-900 min-h-[44px] order-1 sm:order-2"
            >
              {isSubmitting ? "Submitting..." : "Submit Request"}
            </Button>
          </div>
        </form>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};
